version: '3.2'

services:
  es-master:
    build:
      context: es-master/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./es-master/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: bind
        source: /data/elk-data/elasticsearch/es-master
        target: /usr/share/elasticsearch/data
      - type: bind
        source: /data/elk-data/elasticsearch/es-master-logs
        target: /usr/share/elasticsearch/logs
    ports:
      - "19200:9200"
      - "19300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx4g -Xms4g"
      ELASTIC_PASSWORD: changeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk

  es-slave1:
    build:
      context: es-slave1/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./es-slave1/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: bind
        source: /data/elk-data/elasticsearch/es-slave1
        target: /usr/share/elasticsearch/data
      - type: bind
        source: /data/elk-data/elasticsearch/es-slave1-logs
        target: /usr/share/elasticsearch/logs
    ports:
      - "19201:9201"
      - "19301:9301"
    environment:
      ES_JAVA_OPTS: "-Xmx4g -Xms4g"
      ELASTIC_PASSWORD: changeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  
  es-slave2:
    build:
      context: es-slave2/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./es-slave2/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: bind
        source: /data/elk-data/elasticsearch/es-slave2-logs
        target: /usr/share/elasticsearch/logs
    ports:
      - "19202:9202"
      - "19302:9302"
    environment:
      ES_JAVA_OPTS: "-Xmx4g -Xms4g"
      ELASTIC_PASSWORD: changeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk

  logstash:
    build:
      context: ./logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "15000:5000"
      - "19600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      - elk
    depends_on:
      - es-master
      - es-slave1
      - es-slave2

  kibana:
    build:
      context: ./kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "15601:5601"
    networks:
      - elk
    depends_on:
      - es-master
      - es-slave1
      - es-slave2

networks:
  elk:
    driver: bridge
